language: python
python:
  - "3.6"
install: sudo apt-get install libpoppler-cpp-dev && pip install -r requirements-dev.txt
script:  ./manage.py test lcctoolkit
after_success: coveralls
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro