language: python
python:
  - "3.6"
install: pip install -r requirements-dev.txt
script:  ./manage.py test lcctoolkit
after_success: coveralls
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro