version: '3'

services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: lcct
        POSTGRES_PASSWORD: Admin123
  grunt:
    build: .
    command: grunt
    volumes:
      - .:/code
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - grunt
