version: '2'

services:

  nginx:
    container_name: lcct.nginx

  web:
    image: eaudeweb/lcc-toolkit:develop
    container_name: lcct.web
    ports:
      - "127.0.0.1:8000:80"
    environment:
      - DJANGO_MANAGEPY_MIGRATE=on
      - DJANGO_MANAGEPY_COLLECTSTATIC=on
      - DJANGO_MANAGEPY_LOADFIXTURES=on

  elasticsearch:
    container_name: lcct.elastic
    ports:
      - "127.0.0.1:9200:9200"

  db:
    container_name: lcct.db

  logspout:
    image: gliderlabs/logspout:v3.2.3
    container_name: lcct.logs
    environment:
      - HOST=logsN.papertrailapp.com
      - PORT=XXXXX
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    command: 'syslog://$${HOST}:$${PORT}?filter.name=lcct.*'

volumes:
  data:
    driver: local
  static-files:
    driver: local
