version: '2'

services:

  web:
    build: .
    container_name: lcct.web
    ports:
      - "8000:80"
    environment:
      - DJANGO_MANAGEPY_MIGRATE=on
      - DJANGO_MANAGEPY_COLLECTSTATIC=off
      - DJANGO_MANAGEPY_LOADFIXTURES=on
    depends_on:
      - db
      - grunt
    volumes:
      - ./lcctoolkit:/opt/lcct/lcctoolkit
      - ./assets:/opt/lcct/assets
      - ./static:/opt/lcct/static

  elasticsearch:
    container_name: lcct.elastic
    ports:
      - "9200:9200"

  grunt:
    build: .
    container_name: lcct.grunt
    environment:
      - NODE_ENV=dev
    entrypoint: ["grunt"]
    volumes:
      - ./lcctoolkit:/opt/lcct/lcctoolkit
      - ./assets:/opt/lcct/assets
      - ./static:/opt/lcct/static
